// This file should be auto-generated by Supabase CLI: npx supabase gen types typescript
// Updated to match @supabase/supabase-js v2 format

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      daily_suggestions: {
        Row: {
          id: string;
          user_id: string;
          recipe_data: Json;
          generated_at: string;
          expires_at: string;
          saved_recipe_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_data: Json;
          generated_at?: string;
          expires_at: string;
          saved_recipe_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          recipe_data?: Json;
          generated_at?: string;
          expires_at?: string;
          saved_recipe_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "daily_suggestions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "daily_suggestions_saved_recipe_id_fkey";
            columns: ["saved_recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      feed_recipes: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          calories: number | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          servings: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          calories?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          calories?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      feed_recipe_media: {
        Row: {
          id: string;
          feed_recipe_id: string;
          position: number;
          media_type: string;
          url: string;
          name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          feed_recipe_id: string;
          position: number;
          media_type: string;
          url: string;
          name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          feed_recipe_id?: string;
          position?: number;
          media_type?: string;
          url?: string;
          name?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "feed_recipe_media_feed_recipe_id_fkey";
            columns: ["feed_recipe_id"];
            isOneToOne: false;
            referencedRelation: "feed_recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      feed_recipe_ingredients: {
        Row: {
          id: string;
          feed_recipe_id: string;
          position: number;
          raw_text: string;
          quantity: number | null;
          unit: string | null;
          ingredient_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          feed_recipe_id: string;
          position: number;
          raw_text: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          feed_recipe_id?: string;
          position?: number;
          raw_text?: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient_name?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "feed_recipe_ingredients_feed_recipe_id_fkey";
            columns: ["feed_recipe_id"];
            isOneToOne: false;
            referencedRelation: "feed_recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      feed_recipe_steps: {
        Row: {
          id: string;
          feed_recipe_id: string;
          position: number;
          instruction: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          feed_recipe_id: string;
          position: number;
          instruction: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          feed_recipe_id?: string;
          position?: number;
          instruction?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "feed_recipe_steps_feed_recipe_id_fkey";
            columns: ["feed_recipe_id"];
            isOneToOne: false;
            referencedRelation: "feed_recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      import_jobs: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          status: string;
          input_url: string | null;
          input_image_path: string | null;
          result_recipe_id: string | null;
          error_message: string | null;
          retries: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          status?: string;
          input_url?: string | null;
          input_image_path?: string | null;
          result_recipe_id?: string | null;
          error_message?: string | null;
          retries?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          status?: string;
          input_url?: string | null;
          input_image_path?: string | null;
          result_recipe_id?: string | null;
          error_message?: string | null;
          retries?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "import_jobs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "import_jobs_result_recipe_id_fkey";
            columns: ["result_recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          raw_text: string;
          quantity: number | null;
          unit: string | null;
          ingredient_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          raw_text: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          position?: number;
          raw_text?: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient_name?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_ingredients_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_media: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          media_type: string;
          url: string;
          name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          media_type: string;
          url: string;
          name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          position?: number;
          media_type?: string;
          url?: string;
          name?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_media_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      recipe_steps: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          instruction: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          instruction: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          position?: number;
          instruction?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_steps_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      recipes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          source_type: string;
          source_url: string | null;
          source_feed_recipe_id: string | null;
          image_path: string | null;
          calories: number | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          servings: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          source_type: string;
          source_url?: string | null;
          source_feed_recipe_id?: string | null;
          image_path?: string | null;
          calories?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          source_type?: string;
          source_url?: string | null;
          source_feed_recipe_id?: string | null;
          image_path?: string | null;
          calories?: number | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "recipes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "fk_recipes_source_feed_recipe";
            columns: ["source_feed_recipe_id"];
            isOneToOne: false;
            referencedRelation: "feed_recipes";
            referencedColumns: ["id"];
          }
        ];
      };
      usage_counters: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          imports_count: number;
          ai_generations_count: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          date?: string;
          imports_count?: number;
          ai_generations_count?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          imports_count?: number;
          ai_generations_count?: number;
        };
        Relationships: [
          {
            foreignKeyName: "usage_counters_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      user_preferences: {
        Row: {
          user_id: string;
          daily_ai_enabled: boolean;
          dietary_restrictions: string[];
          preferred_cuisines: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          daily_ai_enabled?: boolean;
          dietary_restrictions?: string[];
          preferred_cuisines?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          daily_ai_enabled?: boolean;
          dietary_restrictions?: string[];
          preferred_cuisines?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database[Extract<keyof Database, "public">];

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] &
      PublicSchema["Views"])
  ? (PublicSchema["Tables"] &
      PublicSchema["Views"])[PublicTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
      Insert: infer I;
    }
    ? I
    : never
  : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema["Tables"]
  ? PublicSchema["Tables"][PublicTableNameOrOptions] extends {
      Update: infer U;
    }
    ? U
    : never
  : never;

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema["Enums"]
  ? PublicSchema["Enums"][PublicEnumNameOrOptions]
  : never;
