// This file will be auto-generated by Supabase CLI: npx supabase gen types typescript
// For now, we define a placeholder that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      recipes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          source_type: 'manual' | 'url' | 'image' | 'ai';
          source_url: string | null;
          image_path: string | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          servings: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          source_type: 'manual' | 'url' | 'image' | 'ai';
          source_url?: string | null;
          image_path?: string | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          source_type?: 'manual' | 'url' | 'image' | 'ai';
          source_url?: string | null;
          image_path?: string | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          raw_text: string;
          quantity: number | null;
          unit: string | null;
          ingredient_name: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          raw_text: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient_name?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          position?: number;
          raw_text?: string;
          quantity?: number | null;
          unit?: string | null;
          ingredient_name?: string | null;
          created_at?: string;
        };
      };
      recipe_steps: {
        Row: {
          id: string;
          recipe_id: string;
          position: number;
          instruction: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          position: number;
          instruction: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          position?: number;
          instruction?: string;
          created_at?: string;
        };
      };
      import_jobs: {
        Row: {
          id: string;
          user_id: string;
          type: 'url' | 'image';
          status: 'pending' | 'processing' | 'completed' | 'failed';
          input_url: string | null;
          input_image_path: string | null;
          result_recipe_id: string | null;
          error_message: string | null;
          retries: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: 'url' | 'image';
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          input_url?: string | null;
          input_image_path?: string | null;
          result_recipe_id?: string | null;
          error_message?: string | null;
          retries?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: 'url' | 'image';
          status?: 'pending' | 'processing' | 'completed' | 'failed';
          input_url?: string | null;
          input_image_path?: string | null;
          result_recipe_id?: string | null;
          error_message?: string | null;
          retries?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_preferences: {
        Row: {
          user_id: string;
          daily_ai_enabled: boolean;
          dietary_restrictions: string[];
          preferred_cuisines: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          daily_ai_enabled?: boolean;
          dietary_restrictions?: string[];
          preferred_cuisines?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          daily_ai_enabled?: boolean;
          dietary_restrictions?: string[];
          preferred_cuisines?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      daily_suggestions: {
        Row: {
          id: string;
          user_id: string;
          recipe_data: Json;
          generated_at: string;
          expires_at: string;
          saved_recipe_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          recipe_data: Json;
          generated_at?: string;
          expires_at: string;
          saved_recipe_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          recipe_data?: Json;
          generated_at?: string;
          expires_at?: string;
          saved_recipe_id?: string | null;
        };
      };
      usage_counters: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          imports_count: number;
          ai_generations_count: number;
        };
        Insert: {
          id?: string;
          user_id: string;
          date?: string;
          imports_count?: number;
          ai_generations_count?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          imports_count?: number;
          ai_generations_count?: number;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}



